/*
Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.

1.在一次循环里同时加入和减去出现的字母，则最后唯一在t中出现的那个字母对应的值为-1。
2.最优解：怎么没想到异或运算ORZ。

*/

class Solution {
    public char findTheDifference(String s, String t) {
        char[] c_s = s.toCharArray();
        char[] c_t = t.toCharArray();
        int[] map = new int[28];
        for(int i = 0; i < c_s.length; i ++){
            map[c_s[i] - 97] ++;
            map[c_t[i] - 97] --;
        }
        map[c_t[c_t.length - 1] - 97] --;
        for(char i = 'a'; i <= 'z'; i ++){
            if(map[i - 97] == -1)return i;
        }
        return ' ';
    }
}

class Solution {
    public char findTheDifference(String s, String t) {
        char c = 0;
        char[] ss = s.toCharArray();
        char[] tt = t.toCharArray();
        for (int i = 0; i < ss.length; i++) {
            c ^= ss[i];
            c ^= tt[i];
        }
        c ^= tt[tt.length - 1];
        return c;
    }
}